BEGIN;

CREATE TABLE usuarios (
    id uuid NOT NULL,
    nome_usuario varchar(256) NULL,
    nome_usuario_normalizado varchar(256) NULL,
    email varchar(256) NULL,
    email_normalizado varchar(256) NULL,
    email_confirmado boolean NOT NULL,
    hash_senha text NULL,
    selo_seguranca text NULL,
    selo_concorrencia text NULL,
    telefone varchar(256) NULL,
    telefone_confirmado boolean NOT NULL,
    dois_fatores_habilitado boolean NOT NULL,
    fim_bloqueio timestamptz NULL,
    bloqueio_habilitado boolean NOT NULL,
    contagem_falhas_acesso integer NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_usuarios_nome_usuario_normalizado
    ON usuarios (nome_usuario_normalizado);

CREATE INDEX ix_usuarios_email_normalizado
    ON usuarios (email_normalizado);

CREATE TABLE usuario_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    usuario_id uuid NOT NULL,
    tipo text NULL,
    valor text NULL,
    CONSTRAINT pk_usuario_claims PRIMARY KEY (id),
    CONSTRAINT fk_usuario_claims_usuarios_usuario_id
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_usuario_claims_usuario_id
    ON usuario_claims (usuario_id);

CREATE TABLE usuario_logins (
    provedor varchar(128) NOT NULL,
    chave_provedor varchar(128) NOT NULL,
    nome_exibicao_provedor text NULL,
    usuario_id uuid NOT NULL,
    CONSTRAINT pk_usuario_logins PRIMARY KEY (provedor, chave_provedor),
    CONSTRAINT fk_usuario_logins_usuarios_usuario_id
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_usuario_logins_usuario_id
    ON usuario_logins (usuario_id);

CREATE TABLE usuario_tokens (
    usuario_id uuid NOT NULL,
    provedor varchar(128) NOT NULL,
    nome varchar(128) NOT NULL,
    valor text NULL,
    CONSTRAINT pk_usuario_tokens PRIMARY KEY (usuario_id, provedor, nome),
    CONSTRAINT fk_usuario_tokens_usuarios_usuario_id
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE usuarios, usuario_claims, usuario_logins, usuario_tokens
    TO bfa_app_role;

GRANT USAGE, SELECT
    ON SEQUENCE usuario_claims_id_seq
    TO bfa_app_role;

INSERT INTO bfa_schema_history (version, descricao)
VALUES ('V002', 'criar identidade');

COMMIT;
